### ISSUE TITLE
xelFinderSession.class.php - fixCookieRegist error

### ISSUE THREAD

**Issue by gigamaster** [nao-pon/xelfinder#13]
Fail to run elfinder, so far, I have to comment fixCookieRegist:
`    /**
     * {@inheritdoc}
     */
    public function __construct()
    {
        parent::__construct();
        $this->fixCookieRegist = false;
        return $this;
    }`

and revert to session_start

**Comment by nao-pon** [comment]
@gigamaster This is fixed in my local repository as follows: Included in the next push.

Thanks! 👍 

```php
class xelFinderSession extends elFinderSession
{
    /**
     * {@inheritdoc}
     */
    public function __construct($opts)
    {
        parent::__construct($opts);
        $this->fixCookieRegist = false;
        return $this;
    }
}
```

**Comment by gigamaster** [comment]
I will try this fix. Thanks again ^_^/
