### ISSUE TITLE
WARNING - Admin failed to open googledrive.php

### ISSUE THREAD

**Issue by gigamaster** [nao-pon/xelfinder#14]
WARNING: require(/.../xoops_trust_path/modules/xelfinder/plugins/vendor/autoload.php): 
failed to open stream: No such file or directory in /.../xoops_trust_path/modules/xelfinder/admin/googledrive.php on line 6

Result blank page  ! 
Then...

require XOOPS_TRUST_PATH . '/libs/elfinder/php/autoload.php';

Display page with settings.

**Comment by nao-pon** [comment]
@gigamaster In order to use GoogleDrive, composer update is required from the vendor update menu. I fix it to display a message prompting it if it is not running.

Thanks! 👍

**Comment by gigamaster** [comment]
That's great for user experience. Well done ^_^/
